credentials:
  usernames:
    spoon:
      email: rakotomamomjyannicetr@yahoo.fr
      failed_login_attempts: 0
      name: Spoon Consulting User
      password: $2b$12$6AwgCxmGDl5LtOVxNA4uP.9yP82Pq.UF6p1HsOVPXr36wT2LeEY9m

cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name

